services:
  passport3:
    image: ghcr.io/lghs/passport3:preprod
    container_name: passportv3
    ports:
      - '8030:8030'
    env_file:
      - .env
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --label-enable --cleanup
    restart: always
